"""JA3/JA3S + JA4/JA4S fingerprinting (Phase 4 Task 2).

Implemented from the published specifications (no code copied):
- JA3: classic five-field form (version, ciphers, extensions, curves,
  point formats), GREASE stripped. Convention: S. Gibson / common tooling.
- JA4: FoxIO "JA4: TLS Client Fingerprinting"
  (github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md,
  retrieved 2026-10-02): `{t}{ver}{sni}{ciphers:02d}{exts:02d}{alpn}_
  {cipherhash}_{exthash_sigalgshash}` with the documented rules below.
- JA4S: FoxIO server fingerprint. The algorithm text is published only as a
  diagram, so the field layout follows the reference implementation's
  behavior (verified 2026-10-05 against python/ja4.py `to_ja4s` at
  github.com/FoxIO-LLC/ja4, commit-era main; code read, not copied):
  `{t}{ver}{exts:02d}{alpn}_{cipher}_{exthash}` with extensions hashed in
  present order and GREASE values INCLUDED in both the count and the hash
  (reference comment: "include grease values"). This asymmetry with JA4
  (client strips GREASE per the JA4.md spec text) is faithful to the two
  sources, not a choice.

Documented spec-vs-code discrepancy (followed the spec text): for non-ASCII
ALPN endpoints JA4.md prescribes hex-fallback rules (e.g. 0xAB -> "ab");
the reference code substitutes "9". We implement the documented rules.

GREASE (RFC 8701) handling differs by fingerprint family, faithfully to the
sources: JA4/JA3 (client) strip GREASE before hashing/counting per the JA4.md
spec text ("ignore GREASE"); JA4S (server) INCLUDES GREASE values in the
extension count and present-order hash per the reference implementation
("include grease values" comment in `to_ja4s`). JA3S strips GREASE (classic
convention, same as JA3).

Self-derived vectors: the test vectors in backend/tests/test_phase4_ja4.py
were generated by this implementation and cross-checked by hand against the
spec examples (not by an independent implementation). They are labeled as
such and prove determinism + spec-shape, not independent correctness.
Property tests (GREASE invariance, ordering rules, truncation, fuzz) carry
the real assurance.
"""
from __future__ import annotations

import hashlib

from app.parsing.handshake import (
    ClientHelloInfo, ServerHelloInfo, is_grease, strip_grease,
)

SPEC = ("FoxIO JA4 technical_details/JA4.md (retrieved 2026-10-02, "
        "re-verified 2026-10-05 and 2026-10-09); reference python/ja4.py + "
        "common.py (read 2026-10-05 and 2026-10-09, not copied; "
        "ja4.py@9cfecc5 2026-09-22, JA4.md@820ec30 2026-01-21); JA3 classic form")

# JA4S GREASE handling. Spec text (JA4.md, client fingerprint) says "ignore
# GREASE values anywhere it sees them" (§Details, cipher/extension counts);
# the document carries no server/JA4S section at all, so the spec text is
# ambiguous for JA4S. Reference code python/ja4.py::to_ja4s explicitly
# INCLUDES them: `ext_len` counts all extensions and the comment reads
# "include grease values" (present-order sha12 likewise unfiltered).
# Per cleanup policy we do NOT guess: behavior lives behind this constant,
# follows the reference implementation, and the claim is marked
# "verified against reference code only, spec text ambiguous".
JA4S_INCLUDE_GREASE = True

_VERSION_MAP = {0x0304: "13", 0x0303: "12", 0x0302: "11", 0x0301: "10",
                0x0300: "s3", 0x0002: "s2",
                0xFEFF: "d1", 0xFEFD: "d2", 0xFEFC: "d3"}


def _hex4(values: list[int]) -> list[str]:
    return [f"{v & 0xFFFF:04x}" for v in values]


def _sha12(parts: list[str]) -> str:
    if not parts:
        return "000000000000"
    return hashlib.sha256(",".join(parts).encode()).hexdigest()[:12]


def _version(ch_version: int | None, offered: list[int]) -> str:
    cands = [v for v in strip_grease(offered or [])]
    if cands:
        top = max(cands)
    else:
        top = ch_version
    return _VERSION_MAP.get(top or 0, "00")


def _alpn2(alpn: list[str]) -> str:
    """First+last alphanumerics of the first ALPN value (spec rules)."""
    if not alpn or not alpn[0]:
        return "00"
    first = alpn[0].encode("latin-1", errors="replace")

    def _edge(b: int, is_first: bool) -> str:
        if 0x30 <= b <= 0x39 or 0x41 <= b <= 0x5A or 0x61 <= b <= 0x7A:
            return chr(b)
        hx = f"{b:02x}"
        return hx[0] if is_first else hx[1]

    if len(first) == 1:
        c = _edge(first[0], True)
        # single char supplies both ends; for non-alnum use hex pair ends
        if len(c) == 1 and c == chr(first[0]) and not (
                0x30 <= first[0] <= 0x39 or 0x41 <= first[0] <= 0x5A
                or 0x61 <= first[0] <= 0x7A):
            hx = f"{first[0]:02x}"
            return hx[0] + hx[1]
        return c + c
    return _edge(first[0], True) + _edge(first[-1], False)


def ja3(ch: ClientHelloInfo) -> str:
    """Classic JA3: version,ciphers,extensions,curves,point-formats.

    Deliberately ORDER-SENSITIVE (offered order, GREASE stripped) — that is
    the classic JA3 behavior and its known brittleness. Use JA4 when order
    should not matter.
    """
    ver = max(strip_grease(ch.offered_versions) or [ch.legacy_version or 0])
    parts = [
        str(ver),
        "-".join(str(v) for v in strip_grease(ch.cipher_suites)),
        "-".join(str(v) for v in strip_grease(_extension_ids(ch))),
        "-".join(str(v) for v in strip_grease(ch.supported_groups)),
        "-".join(str(v) for v in strip_grease(ch.ec_point_formats)),
    ]
    return ",".join(parts)


def ja3_digest(ch: ClientHelloInfo) -> str:
    return hashlib.md5(ja3(ch).encode()).hexdigest()


def _extension_ids(ch: ClientHelloInfo) -> list[int]:
    return list(ch.extension_ids)


def ja4(ch: ClientHelloInfo, quic: bool = False) -> str:
    """JA4 client fingerprint per the published spec."""
    ptype = "q" if quic else "t"
    ver = _version(ch.legacy_version, ch.offered_versions)
    sni = "d" if ch.sni else "i"
    ciphers = strip_grease(ch.cipher_suites)
    exts = strip_grease(ch.extension_ids)
    cipher_n = f"{min(len(ciphers), 99):02d}"
    ext_n = f"{min(len(exts), 99):02d}"
    alpn = _alpn2(ch.alpn)
    cipher_hash = _sha12(sorted(_hex4(ciphers)))
    sigs = list(ch.sig_algs or [])
    ext_nogrease = sorted(_hex4(e for e in exts if e not in (0, 16)))
    if sigs:
        ext_str = ",".join(ext_nogrease) + "_" + ",".join(_hex4(sigs))
        ext_hash = hashlib.sha256(ext_str.encode()).hexdigest()[:12]
    else:
        ext_hash = _sha12(ext_nogrease)
    return f"{ptype}{ver}{sni}{cipher_n}{ext_n}{alpn}_{cipher_hash}_{ext_hash}"


def ja3s(sh: ServerHelloInfo) -> str:
    parts = [
        str(sh.negotiated_version or sh.legacy_version or 0),
        str(sh.cipher_suite or 0),
        "-".join(str(v) for v in strip_grease(sh.extension_ids)),
    ]
    return ",".join(parts)


def ja3s_digest(sh: ServerHelloInfo) -> str:
    return hashlib.md5(ja3s(sh).encode()).hexdigest()


def ja4s(sh: ServerHelloInfo, quic: bool = False) -> str:
    """JA4S server fingerprint.

    Verified 2026-10-05 against the reference implementation's `to_ja4s`
    behavior (code read, not copied): extension count and sha12 cover ALL
    extensions in present order INCLUDING GREASE; single cipher embedded
    unhashed; missing extensions hash to "000000000000". No longer marked
    experimental for layout; ALPN non-ASCII endpoints still follow the spec
    text (hex rules) where the reference code substitutes "9" (documented).
    Claim level: verified against reference code only, spec text ambiguous
    (see JA4S_INCLUDE_GREASE).
    """
    ptype = "q" if quic else "t"
    ver = _VERSION_MAP.get(sh.negotiated_version or sh.legacy_version or 0, "00")
    if JA4S_INCLUDE_GREASE:
        exts = list(sh.extension_ids)  # present order, GREASE included (reference parity)
    else:
        exts = strip_grease(sh.extension_ids)
    ext_n = f"{min(len(exts), 99):02d}"
    alpn = _alpn2(sh.alpn or [])
    cipher = f"{(sh.cipher_suite or 0) & 0xFFFF:04x}"
    ext_hash = _sha12(_hex4(exts))
    return f"{ptype}{ver}{ext_n}{alpn}_{cipher}_{ext_hash}"
