"""Phase 4 Task 2: JA3/JA4 correctness, storage, deny lists, inventory.

Fingerprint test vectors below are SELF-DERIVED (generated by this
implementation; the sha256 halves match the two intermediate values published
in the FoxIO JA4 spec: 8daaf6152771 and e5627efa2ab1). They prove
determinism and spec-shape conformance, not independent verification.
"""
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import hashlib


def _ch(ciphers=(0x1301, 0x1302), exts=(0, 10, 16, 43, 13), groups=(29,),
        sigalgs=(0x0403,), sni="mail.example.com", alpn=("h2",), versions=(0x0304, 0x0303)):
    from app.parsing.handshake import ClientHelloInfo
    return ClientHelloInfo(
        offered_versions=list(versions), legacy_version=0x0303,
        cipher_suites=list(ciphers), sni=sni, alpn=list(alpn),
        supported_groups=list(groups), has_supported_versions=True,
        key_share_groups=list(groups), sig_algs=list(sigalgs),
        extension_ids=list(exts), ec_point_formats=[0])


def test_ja4_shape_and_grease_invariance():
    from app.parsing import ja4 as J
    ch = _ch()
    fp = J.ja4(ch)
    parts = fp.split("_")
    assert len(parts) == 3 and fp.startswith("t13d")
    assert len(parts[1]) == 12 and len(parts[2]) == 12
    # GREASE anywhere must not change the fingerprint
    ch_g = _ch(ciphers=(0x0A0A, 0x1301, 0x1302, 0x1A1A),
               exts=(0, 10, 0x2A2A, 16, 43, 13), groups=(29, 0x3A3A))
    assert J.ja4(ch_g) == fp
    assert J.ja3(ch_g) == J.ja3(ch)


def test_ja4_ordering_rules():
    from app.parsing import ja4 as J
    # JA4 sorts extensions; classic JA3 preserves offered order.
    a = _ch(exts=(0, 10, 16, 43, 13))
    b = _ch(exts=(13, 43, 16, 10, 0))
    assert J.ja4(a) == J.ja4(b)
    assert J.ja3(a) != J.ja3(b)  # JA3 is order-sensitive by design
    no_sni = _ch(sni=None)
    assert J.ja4(no_sni)[3] == "i"
    assert J.ja4(no_sni) != J.ja4(a)
    # ALPN changes the fingerprint (first/last chars captured)
    assert J.ja4(_ch(alpn=("http/1.1",))) != fp if (fp := J.ja4(a)) else False


def test_ja4_spec_hash_halves_match_published():
    # The only independently verifiable anchors: the two intermediate hashes
    # printed in the FoxIO JA4 spec document itself.
    assert hashlib.sha256(
        "002f,0035,009c,009d,1301,1302,1303,c013,c014,c02b,c02c,c02f,c030,cca8,cca9"
        .encode()).hexdigest()[:12] == "8daaf6152771"
    assert hashlib.sha256(
        ("0005,000a,000b,000d,0012,0015,0017,001b,0023,002b,002d,0033,4469,ff01"
         "_0403,0804,0401,0503,0805,0501,0806,0601").encode()).hexdigest()[:12] == "e5627efa2ab1"


def test_truncated_hello_fingerprints_gracefully():
    from app.parsing import ja4 as J
    from app.parsing.handshake import ClientHelloInfo
    empty = ClientHelloInfo()
    assert J.ja4(empty).startswith("t00i0000")
    assert J.ja3(empty).startswith("0,")
    assert "000000000000" in J.ja4(empty)


def test_ja4s_and_ja3s_from_server_hello():
    from app.parsing import ja4 as J
    from app.parsing.handshake import ServerHelloInfo
    sh = ServerHelloInfo(negotiated_version=0x0304, cipher_suite=0x1301,
                         extension_ids=[43, 51], alpn=["h2"])
    fp = J.ja4s(sh)
    assert fp.startswith("s13") and "_1301_" in fp
    assert len(fp.split("_")) == 3  # EXPERIMENTAL layout documented in ja4.py
    assert len(J.ja3s_digest(sh)) == 32


def test_fuzz_fingerprint_never_raises():
    from hypothesis import given, settings as _hs, strategies as st
    from app.parsing import ja4 as J
    from app.parsing.handshake import ClientHelloInfo, ServerHelloInfo

    @_hs(max_examples=200, derandomize=True)
    @given(st.lists(st.integers(0, 0xFFFF), max_size=40),
           st.lists(st.integers(0, 0xFFFF), max_size=40),
           st.lists(st.integers(0, 0xFFFF), max_size=12))
    def _fuzz(ciphers, exts, groups):
        ch = ClientHelloInfo(cipher_suites=ciphers, supported_groups=groups,
                             extension_ids=exts, sig_algs=groups)
        J.ja4(ch)
        J.ja3(ch)
        J.ja3_digest(ch)
        sh = ServerHelloInfo(cipher_suite=ciphers[0] if ciphers else 0,
                             extension_ids=exts)
        J.ja4s(sh)
        J.ja3s(sh)

    _fuzz()


def test_deny_list_match_and_org_isolation():
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    from app.core.database import Base
    import app.models.entities as E
    from app.live.flows import _deny_list_hit, _deny_cache
    _deny_cache.clear()
    engine = create_engine("sqlite://")
    Base.metadata.create_all(engine)
    S = sessionmaker(bind=engine)()
    S.add(E.Organization(id="o1", name="a"))
    S.add(E.Organization(id="o2", name="b"))
    S.add(E.FingerprintList(org_id="o1", kind="deny", fp_type="ja4",
                            value="fp-bad", source="soc", comment="x",
                            created_by="a"))
    S.commit()
    assert _deny_list_hit(S, "o1", {"ja4": "fp-bad"}) == "ja4:fp-bad"
    assert _deny_list_hit(S, "o1", {"ja4": "fp-ok"}) is None
    assert _deny_list_hit(S, "o2", {"ja4": "fp-bad"}) is None  # other org unaffected
    S.close()


def test_outdated_stack_signal_and_inventory():
    from app.parsing.rules import SessionAnalysis, run_rules
    sa = SessionAnalysis(session_id="t", protocol="SMTP",
                         five_tuple="a:1-b:25", is_starttls=False)
    from app.parsing.handshake import ClientHelloInfo
    sa.client_hello = ClientHelloInfo(offered_versions=[0x0301], legacy_version=0x0301)
    run_rules(sa)
    assert "outdated-client-stack" in {f.rule_id for f in sa.findings}
    sa2 = SessionAnalysis(session_id="t", protocol="SMTP",
                          five_tuple="a:1-b:25", is_starttls=False)
    sa2.client_hello = ClientHelloInfo(offered_versions=[0x0304, 0x0303], legacy_version=0x0303)
    run_rules(sa2)
    assert "outdated-client-stack" not in {f.rule_id for f in sa2.findings}
