"""Phase 4 Task 2: JA3/JA4 correctness, storage, deny lists, inventory.

Fingerprint test vectors below are SELF-DERIVED (generated by this
implementation; the sha256 halves match the two intermediate values published
in the FoxIO JA4 spec: 8daaf6152771 and e5627efa2ab1). They prove
determinism and spec-shape conformance, not independent verification.
"""
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend")))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import hashlib


def _ch(ciphers=(0x1301, 0x1302), exts=(0, 10, 16, 43, 13), groups=(29,),
        sigalgs=(0x0403,), sni="mail.example.com", alpn=("h2",), versions=(0x0304, 0x0303)):
    from app.parsing.handshake import ClientHelloInfo
    return ClientHelloInfo(
        offered_versions=list(versions), legacy_version=0x0303,
        cipher_suites=list(ciphers), sni=sni, alpn=list(alpn),
        supported_groups=list(groups), has_supported_versions=True,
        key_share_groups=list(groups), sig_algs=list(sigalgs),
        extension_ids=list(exts), ec_point_formats=[0])


def test_ja4_shape_and_grease_invariance():
    from app.parsing import ja4 as J
    ch = _ch()
    fp = J.ja4(ch)
    parts = fp.split("_")
    assert len(parts) == 3 and fp.startswith("t13d")
    assert len(parts[1]) == 12 and len(parts[2]) == 12
    # GREASE anywhere must not change the fingerprint
    ch_g = _ch(ciphers=(0x0A0A, 0x1301, 0x1302, 0x1A1A),
               exts=(0, 10, 0x2A2A, 16, 43, 13), groups=(29, 0x3A3A))
    assert J.ja4(ch_g) == fp
    assert J.ja3(ch_g) == J.ja3(ch)


def test_ja4_ordering_rules():
    from app.parsing import ja4 as J
    # JA4 sorts extensions; classic JA3 preserves offered order.
    a = _ch(exts=(0, 10, 16, 43, 13))
    b = _ch(exts=(13, 43, 16, 10, 0))
    assert J.ja4(a) == J.ja4(b)
    assert J.ja3(a) != J.ja3(b)  # JA3 is order-sensitive by design
    no_sni = _ch(sni=None)
    assert J.ja4(no_sni)[3] == "i"
    assert J.ja4(no_sni) != J.ja4(a)
    # ALPN changes the fingerprint (first/last chars captured)
    assert J.ja4(_ch(alpn=("http/1.1",))) != fp if (fp := J.ja4(a)) else False


def test_ja4_spec_hash_halves_match_published():
    # The only independently verifiable anchors: the two intermediate hashes
    # printed in the FoxIO JA4 spec document itself.
    assert hashlib.sha256(
        "002f,0035,009c,009d,1301,1302,1303,c013,c014,c02b,c02c,c02f,c030,cca8,cca9"
        .encode()).hexdigest()[:12] == "8daaf6152771"
    assert hashlib.sha256(
        ("0005,000a,000b,000d,0012,0015,0017,001b,0023,002b,002d,0033,4469,ff01"
         "_0403,0804,0401,0503,0805,0501,0806,0601").encode()).hexdigest()[:12] == "e5627efa2ab1"


def test_truncated_hello_fingerprints_gracefully():
    from app.parsing import ja4 as J
    from app.parsing.handshake import ClientHelloInfo
    empty = ClientHelloInfo()
    assert J.ja4(empty).startswith("t00i0000")
    assert J.ja3(empty).startswith("0,")
    assert "000000000000" in J.ja4(empty)


def test_pq_offered_negotiated_and_hrr():
    from app.parsing.handshake import pq_status, is_pq_group
    assert is_pq_group(4588) and is_pq_group(513)
    assert not is_pq_group(29) and not is_pq_group(25497)
    s = pq_status([29, 4588], 4588)
    assert s["offered_pq"] and s["negotiated_pq"]
    assert s["selected"] == "X25519MLKEM768 (hybrid PQ)"
    s2 = pq_status([29, 4588], 29)
    assert s2["offered_pq"] and not s2["negotiated_pq"]
    # HRR flow: server asks for a different group than offered highlights gap
    s3 = pq_status([4588], 29)
    assert s3["offered_pq"] and not s3["negotiated_pq"]
    s4 = pq_status([29], None)
    assert not s4["offered_pq"] and not s4["negotiated_pq"]


def test_quantum_posture_api_aggregates_org():
    import asyncio
    from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
    from app.core.database import Base
    import app.models.entities as E
    from datetime import datetime, timezone
    engine = create_async_engine("sqlite+aiosqlite://")
    maker = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async def _init():
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
        async with maker() as s:
            s.add(E.Organization(id="org-a", name="a"))
            s.add(E.AnalysisJob(id="j", filename="x", pcap_path="x",
                                 status=E.JobStatus.COMPLETED, org_id="org-a"))
            pq_yes = {"offered_pq": True, "negotiated_pq": True,
                      "offered": ["x25519", "X25519MLKEM768 (hybrid PQ)"],
                      "selected": "X25519MLKEM768 (hybrid PQ)"}
            pq_gap = {"offered_pq": True, "negotiated_pq": False,
                      "offered": ["X25519MLKEM768 (hybrid PQ)"], "selected": "x25519"}
            s.add(E.Session(id="s1", job_id="j", protocol="SMTP",
                            five_tuple="1.1.1.1:1-2.2.2.2:25", src_ip="a", dst_ip="b",
                            src_port=1, dst_port=25, org_id="org-a",
                            details={"pq": pq_yes}))
            s.add(E.Session(id="s2", job_id="j", protocol="SMTP",
                            five_tuple="1.1.1.1:2-3.3.3.3:25", src_ip="a", dst_ip="c",
                            src_port=1, dst_port=25, org_id="org-a",
                            details={"pq": pq_gap}))
            s.add(E.Session(id="s3", job_id="j", protocol="SMTP",
                            five_tuple="9.9.9.9:1-8.8.8.8:25", src_ip="x", dst_ip="y",
                            src_port=1, dst_port=25, org_id="org-b",
                            details={"pq": pq_yes}))
            await s.commit()

    asyncio.get_event_loop().run_until_complete(_init())
    from app.api.main import app
    from app.core.database import get_db
    from app.core.auth import get_current_user, AuthContext
    from fastapi.testclient import TestClient

    async def _db():
        async with maker() as s:
            yield s

    async def _user():
        return AuthContext(user_id="u", email="a@x", org_id="org-a",
                           role="analyst", via="jwt")

    app.dependency_overrides[get_db] = _db
    app.dependency_overrides[get_current_user] = _user
    try:
        client = TestClient(app, raise_server_exceptions=False)
        r = client.get("/api/v1/posture/quantum")
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["policy"] == "informational"
        assert body["org"]["total"] == 2  # org-b session excluded
        assert body["org"]["pq_negotiated"] == 1
        assert body["org"]["servers_unable"] == ["3.3.3.3"]
        assert body["attention"] == []  # informational: no findings, no list
    finally:
        app.dependency_overrides.pop(get_db, None)
        app.dependency_overrides.pop(get_current_user, None)


def test_ja4s_and_ja3s_from_server_hello():
    from app.parsing import ja4 as J
    from app.parsing.handshake import ServerHelloInfo
    sh = ServerHelloInfo(negotiated_version=0x0304, cipher_suite=0x1301,
                         extension_ids=[43, 51], alpn=["h2"])
    fp = J.ja4s(sh)
    # JA4S field name, but the leading marker is the transport like JA4.
    assert fp.startswith("t13") and "_1301_" in fp
    assert len(fp.split("_")) == 3  # EXPERIMENTAL layout documented in ja4.py
    assert len(J.ja3s_digest(sh)) == 32


def test_ja4_matches_official_spec_worked_example():
    """Item 1 verification: full worked example from FoxIO JA4.md.

    Inputs are the example's printed field lists (offered order); expected
    output is the spec's printed fingerprint. Spec: technical_details/JA4.md
    (retrieved 2026-10-02, re-verified 2026-10-05). License note: FoxIO
    License 1.1 — short factual input/output strings used for verification
    only, no spec text or vectors copied into the repo.
    """
    from app.parsing import ja4 as J
    from app.parsing.handshake import ClientHelloInfo
    ciphers = [0x1301, 0x1302, 0x1303, 0xc02b, 0xc02f, 0xc02c, 0xc030,
               0xcca9, 0xcca8, 0xc013, 0xc014, 0x009c, 0x009d, 0x002f, 0x0035]
    exts = [0x001b, 0x0000, 0x0033, 0x0010, 0x4469, 0x0017, 0x002d, 0x000d,
            0x0005, 0x0023, 0x0012, 0x002b, 0xff01, 0x000b, 0x000a, 0x0015]
    sigalgs = [0x0403, 0x0804, 0x0401, 0x0503, 0x0805, 0x0501, 0x0806, 0x0601]
    ch = ClientHelloInfo(
        offered_versions=[0x0304, 0x0303], legacy_version=0x0303,
        cipher_suites=ciphers, sni="example.com", alpn=["h2"],
        supported_groups=[29], has_supported_versions=True,
        sig_algs=sigalgs, extension_ids=exts, ec_point_formats=[0])
    assert J.ja4(ch) == "t13d1516h2_8daaf6152771_e5627efa2ab1"


def test_ja4s_includes_grease_per_reference():
    """Item 1 fix: reference `to_ja4s` includes GREASE in ext count+hash
    (present order). Verified by code reading 2026-10-05 (not copied)."""
    import hashlib
    from app.parsing import ja4 as J
    from app.parsing.handshake import ServerHelloInfo
    sh = ServerHelloInfo(negotiated_version=0x0304, cipher_suite=0x1301,
                         extension_ids=[43, 51, 0x0A0A], alpn=["h2"])
    got = J.ja4s(sh)
    exp_hash = hashlib.sha256("002b,0033,0a0a".encode()).hexdigest()[:12]
    assert got == f"t1303h2_1301_{exp_hash}"
    # count includes the GREASE extension (03, not 02)
    assert got.split("_")[0] == "t1303h2"


def test_fuzz_fingerprint_never_raises():
    from hypothesis import given, settings as _hs, strategies as st
    from app.parsing import ja4 as J
    from app.parsing.handshake import ClientHelloInfo, ServerHelloInfo

    @_hs(max_examples=200, derandomize=True)
    @given(st.lists(st.integers(0, 0xFFFF), max_size=40),
           st.lists(st.integers(0, 0xFFFF), max_size=40),
           st.lists(st.integers(0, 0xFFFF), max_size=12))
    def _fuzz(ciphers, exts, groups):
        ch = ClientHelloInfo(cipher_suites=ciphers, supported_groups=groups,
                             extension_ids=exts, sig_algs=groups)
        J.ja4(ch)
        J.ja3(ch)
        J.ja3_digest(ch)
        sh = ServerHelloInfo(cipher_suite=ciphers[0] if ciphers else 0,
                             extension_ids=exts)
        J.ja4s(sh)
        J.ja3s(sh)

    _fuzz()


def test_deny_list_match_and_org_isolation():
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    from app.core.database import Base
    import app.models.entities as E
    from app.live.flows import _deny_list_hit, _deny_cache
    _deny_cache.clear()
    engine = create_engine("sqlite://")
    Base.metadata.create_all(engine)
    S = sessionmaker(bind=engine)()
    S.add(E.Organization(id="o1", name="a"))
    S.add(E.Organization(id="o2", name="b"))
    S.add(E.FingerprintList(org_id="o1", kind="deny", fp_type="ja4",
                            value="fp-bad", source="soc", comment="x",
                            created_by="a"))
    S.commit()
    assert _deny_list_hit(S, "o1", {"ja4": "fp-bad"}) == "ja4:fp-bad"
    assert _deny_list_hit(S, "o1", {"ja4": "fp-ok"}) is None
    assert _deny_list_hit(S, "o2", {"ja4": "fp-bad"}) is None  # other org unaffected
    S.close()


def test_outdated_stack_signal_and_inventory():
    from app.parsing.rules import SessionAnalysis, run_rules
    sa = SessionAnalysis(session_id="t", protocol="SMTP",
                         five_tuple="a:1-b:25", is_starttls=False)
    from app.parsing.handshake import ClientHelloInfo
    sa.client_hello = ClientHelloInfo(offered_versions=[0x0301], legacy_version=0x0301)
    run_rules(sa)
    assert "outdated-client-stack" in {f.rule_id for f in sa.findings}
    sa2 = SessionAnalysis(session_id="t", protocol="SMTP",
                          five_tuple="a:1-b:25", is_starttls=False)
    sa2.client_hello = ClientHelloInfo(offered_versions=[0x0304, 0x0303], legacy_version=0x0303)
    run_rules(sa2)
    assert "outdated-client-stack" not in {f.rule_id for f in sa2.findings}


def test_fp_list_crud_is_org_scoped():
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    from app.core.database import Base
    import app.models.entities as E
    engine = create_engine("sqlite://")
    Base.metadata.create_all(engine)
    S = sessionmaker(bind=engine)()
    S.add(E.Organization(id="o1", name="a"))
    S.add(E.FingerprintList(org_id="o1", kind="deny", fp_type="ja4",
                            value="x", source="s", comment="c", created_by="a"))
    S.commit()
    assert S.query(E.FingerprintList).filter_by(org_id="o1").count() == 1
    assert S.query(E.FingerprintList).filter_by(org_id="o2").count() == 0
    S.close()
