"""initial schema matching models

Revision ID: 2fe72d5f9ab3
Revises: 
Create Date: 2026-09-29 08:47:58.933946

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB as _PGJSONB
from app.core.database import JSONBType as _JSONBType


revision: str = '2fe72d5f9ab3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=512), nullable=False),
    sa.Column('detail', _JSONBType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('pcap_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_org_id'), 'analysis_jobs', ['org_id'], unique=False)
    op.create_table('tracked_certs',
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('subject_cn', sa.String(length=512), nullable=False),
    sa.Column('issuer_cn', sa.String(length=512), nullable=False),
    sa.Column('sans', _JSONBType(), nullable=True),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('not_after', sa.DateTime(), nullable=True),
    sa.Column('pubkey_alg', sa.String(length=64), nullable=False),
    sa.Column('pubkey_bits', sa.Integer(), nullable=True),
    sa.Column('signature_alg', sa.String(length=128), nullable=False),
    sa.Column('is_self_signed', sa.Boolean(), nullable=False),
    sa.Column('chain_result', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('expiry_alerted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_index(op.f('ix_tracked_certs_org_id'), 'tracked_certs', ['org_id'], unique=False)
    op.create_index('ix_trackedcert_org_notafter', 'tracked_certs', ['org_id', 'not_after'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('org_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('session_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_summaries_job_id'), 'session_summaries', ['job_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('five_tuple', sa.String(length=512), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=False),
    sa.Column('dst_ip', sa.String(length=64), nullable=False),
    sa.Column('src_port', sa.Integer(), nullable=False),
    sa.Column('dst_port', sa.Integer(), nullable=False),
    sa.Column('is_starttls', sa.Boolean(), nullable=False),
    sa.Column('transition_offset', sa.Integer(), nullable=True),
    sa.Column('tls_version', sa.String(length=32), nullable=True),
    sa.Column('negotiated_cipher', sa.String(length=128), nullable=True),
    sa.Column('cipher_strength', sa.Float(), nullable=True),
    sa.Column('key_length', sa.Integer(), nullable=True),
    sa.Column('pfs_supported', sa.Boolean(), nullable=True),
    sa.Column('cert_chain_valid', sa.Boolean(), nullable=True),
    sa.Column('cert_age_days', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('overall_finding_count', sa.Integer(), nullable=False),
    sa.Column('max_severity', sa.String(length=16), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('org_id', sa.String(length=64), nullable=True),
    sa.Column('details', _JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_job', 'sessions', ['job_id'], unique=False)
    op.create_index(op.f('ix_sessions_job_id'), 'sessions', ['job_id'], unique=False)
    op.create_index(op.f('ix_sessions_org_id'), 'sessions', ['org_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=False),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evidence', _JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_session_id'), 'findings', ['session_id'], unique=False)
    op.create_table('shap_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('feature', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shap_rows_session_id'), 'shap_rows', ['session_id'], unique=False)
    # Raw-DDL tables (created lazily via text() in app code; folded in here):
    # - alerts (live dispatcher + API history)
    # - baseline_features (rolling ML baseline store)
    op.create_table('alerts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('five_tuple', sa.Text(), nullable=True),
    sa.Column('payload', _JSONBType(), nullable=True),
    sa.Column('org_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('features', _JSONBType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shap_rows_session_id'), table_name='shap_rows')
    op.drop_table('shap_rows')
    op.drop_index(op.f('ix_findings_session_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_sessions_org_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_job_id'), table_name='sessions')
    op.drop_index('ix_session_job', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_session_summaries_job_id'), table_name='session_summaries')
    op.drop_table('session_summaries')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_trackedcert_org_notafter', table_name='tracked_certs')
    op.drop_index(op.f('ix_tracked_certs_org_id'), table_name='tracked_certs')
    op.drop_table('tracked_certs')
    op.drop_index(op.f('ix_analysis_jobs_org_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
